config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users
  resources :photos do
    resources :comments
  end
  get 'home/index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :photo
  validates :content, presence: true
end

app/models/photo.rb
class Photo < ApplicationRecord
  has_many :comments
  validates :title, presence: true
  has_many_attached :images
end 

app/models/user.rb
class User < ApplicationRecord
  has_many_attached :images
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [ :index]

  def home
  end

  def about
  end

  def contact
  end

  def secret
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @photo = Comment.find(params[:photo_id])
    comments = Comment.all
  end

  def new
    @photo = Comment.find(params[:photo_id])
    @comment = @photo.comments.new
  end

  def create
    @photo = Comment.find([:photo_id])
    @comment = @photo.comments.new(comment_params)
    if @comment.save
      redirect_to photo_path(@comment.photo)
    else
      render :new
    end
  end

 def show
  @photo = Comment.find(params[:photo_id])
  render "photos/show"
 end

  def edit
    @comment = Comment.find(params[:id])
    @photo = Comment.find(params[:photo_id])
    render :edit
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to photo_comment_path
    else
      render :edit
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to photo_path(@comment.photo)
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :user_id, :photo_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.all
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    @photo.images.attach(params[:photo][:image])
    if @photo.save
      flash[:notice] = "Your Photo has been saved"
      redirect_to photos_path
    else
      flash[:notice] = "Whoops something went wrong your photo did not save"
      render :new
    end
  end

  def show
    @photo = Photo.find(params[:id])
    render :show
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def update
    @photo = Photo.find(params[:id])
    if @photo.update(photo_params)
      redirect_to photos_path
    else
      render :edit
    end
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    redirect_to "/photos"
  end

  private

  def photo_params
    params.require(:photo).permit(:title, images: [])
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/comments/_form.html.erb
<%= form_for @comment, html: { multipart: true } do |f| %>
  <%= f.file_field :comment %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit comment</h1>


<%= render "comments/form" %>

app/views/comments/index.html.erb
<ul>
  <% @comments.each do |comment| %>
  <li> <%= link_to  comment.content, comment_path(comment) %></li>
  <% end %>

  </ul>

app/views/comments/new.html.erb
<h1>New comment<h1>

<%= render "comments/form"%>

app/views/home/index.html.erb
<h1>Welcome to the homepage</h1>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Find your Inspiration | Flickr</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
  <h1>flickr</h1>
  <div class="container">
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <h1 class="navbar-brand"></h1>
        </div>
        <ul class="nav navbar-nav">
          <li class="link"><a href="/">Home</a></li>
          <li class="link"><a href="/photos/new">Add a photo</a></li>
          <li class="link"><a href="/users/sign_in">Sign in</a></li>
          <li class="link"><a href="/users/sign_up">Sign up</a></li>
          <li class="link"><%= link_to "Sign Out", destroy_user_session_path, :method => 'delete'%></li>
          <li class="link"><a href="/photos">Photos</a></li>
        </ul>
      </div>
    </nav>
    
  </div>
  <%= flash[:alert] %>
  <%= flash[:notice] %>
    <%= yield %>
    
  </body>
</html>

app/views/photos/_form.html.erb
<%= render "layouts/errors", :object => @photo %>

<%= form_for @photo, html: { multipart: true } do |f| %>
  <%= f.file_field :image %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.submit %>
<% end %>

app/views/photos/edit.html.erb
<h1>Edit photo</h1>


<%= render "photos/form" %>

app/views/photos/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flickr New</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
  <h1>Your Photos</h1>
  
        <ul class="nav navbar-nav">
          <% @photos.each do |photo| %>
          <li><%= link_to photo.title, photo_path(photo) %></li> 
          <li><%= link_to photo.images, photo_path(photo) %></li>
        <% end %> 
         </ul>
        
  <%= yield %>
    
  </body>
</html>

app/views/photos/new.html.erb
<h1>New Photo</h1>

<%= form_for @photo do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :image %>
  <%= f.file_field :image %>
  <br>
  <%= f.submit %>
<% end %>

app/views/photos/show.html.erb
<h1><%= @photo.title %></h1>


<% if @photo.images.attached? %>
  <% @photo.images.each do |file| %>
    <ul>
      <li>
      <%= image_tag file%>
      </li>
    </ul>
  <% end %>
<% else %>
<p>No pics yet.</p>
<% end %>